name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      PACKAGE_NAME: SpotifyAppleMusicSync

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Build
      run: brew bundle
    - name: Build
      run: swift build -v
    - name: Lint
      run: swiftformat --lint . && swiftlint
    - name: Run tests
      run: swift test --verbose --enable-code-coverage
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash) -F github -F macOS -n ${{ github.sha }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Build Documentation
      run: sourcedocs generate --spm-module ${{ env.PACKAGE_NAME }}
    - name: Verify Valid Swift Package
      run: curl -s https://raw.githubusercontent.com/daveverwer/SwiftPMLibrary/master/script.sh | bash -s -- mine
    - name: CocoaPods Action
      run: pod lib lint
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add Documentation
        git diff-index --quiet HEAD || git commit -m "[github action] Update Docs"
        git push
